# Project 2: True Photomosaic
#
# Collaboration Statement here: 
#
# David Maldonado & Roberto Vargas
#links to resources used:
#https://stackoverflow.com/questions/3019909/using-an-index-to-get-an-item-python
#https://pypi.python.org/pypi/python-resize-image
#https://stackoverflow.com/questions/3207219/how-do-i-list-all-files-of-a-directory
#https://stackoverflow.com/questions/33689705/how-to-compare-values-in-tuples-in-a-list
#image database: https://github.com/caesar0301/awesome-public-datasets#image-processing

from __future__ import print_function
import cv2
import numpy as np
from PIL import Image

#setup the output image information
output_dims = (2500, 2500)
output_image = Image.new("RGB", output_dims)
#set the initial x and y coordinates to the beginning of the image
x = 0
y = 0

#determine the path where the image text files are located
filepath = "C:\\Users\\Nzxt\\Desktop\\project2\\"
#open the file path with the list of tuples from a text file generated by the other program
f = open("C:\\Users\\Nzxt\\Desktop\\project2\\image_tuples.txt")

#create an empty list
tuple_list =[]
#append each tuple to the list
for line in f:
    tup = eval(line)
    tuple_list.append(tup)
#create a list of image names from a text file generated by the other program
name_list = open("C:\\Users\\Nzxt\\Desktop\\project2\\image_names.txt").readlines()

#read in the main image to be mosaiced
mosaic_in = cv2.imread("C:\\Users\\Nzxt\\Desktop\\project2\\test\\mos_image\\mosaic_test.jpg")
mosaic_in = np.array(mosaic_in)
#determine the size of the mosaic image
rows,cols, colors = mosaic_in.shape

#loop through the image
for i in range(rows):
    for j in range(cols):
        #look at the current pixel
        current_pixel = mosaic_in[i,j]
        #find the tuple with the minimum distance from the current pixel
        next_image = min(tuple_list, key=lambda c: (c[0]- current_pixel[0])**2 + (c[1]-current_pixel[1])**2 + (c[2]-current_pixel[2])**2)
        #get the index of the tuple from the list
        next_image_index = tuple_list.index(next_image)
        #set the tuple index to the same as the one in the name list
        next_image_name = name_list[next_image_index]
        #remove the newline character
        next_image_name = next_image_name.strip()
        #open the image to be used as part of the mosaic
        the_image = Image.open(next_image_name)
        #resize the image to 25x25
        the_image = the_image.resize((25, 25))
        #paste the image in it's spot
        output_image.paste(the_image, (x, y))
        #move through the image based on the size of the image being used
        if x >= 2474:
            x = 0
            y = y + 25
        else:
            x = x + 25
#save the final image
output_image.save("C:\\Users\\Nzxt\\Desktop\\project2\\test\\mos_image\\mosaic_test_output.jpg")





      



        
        

                

        
        
        
        
        
        
        

        
        
        
        

        